### ISSUE TITLE
Comments: Bitcoin Is Not The Future Of Currency

### ISSUE THREAD

**Issue by valeIT** [valeIT/valeIT.github.io#12]
Link: http://www.valentinourbano.com/Bitcoin-is-not-the-future-of-currencies.html

**Comment by HueyGeek** [comment]
Must interesting your article, I think almost exactly the same.

By the way, I'm writing to you because Facebook and Google links in the last paragraph are exchanged.

**Comment by valeIT** [comment]
Thanks, will fix it!
