### ISSUE TITLE
Comments: Free My Desktop - Free Mac App

### ISSUE THREAD

**Issue by valeIT** [valeIT/valeIT.github.io#14]
Link: http://www.valentinourbano.com/Free-my-desktop-mac-app.html

**Comment by alxndrsbrwn** [comment]
I like the app! Are there plans to include new features?

**Comment by valeIT** [comment]
Hey, thanks! I would like to keep it pretty minimal so nothing in the works as of now. But if you or anyone else has any idea on something neat to add please do let me know!

**Comment by alxndrsbrwn** [comment]
Just a couple of UX thoughts ... maybe some options for auto-update & hiding from the dock. Also, the icon doesn't really do justice to what the app does.

**Comment by valeIT** [comment]
The icons plainly sucks, I agree. Will add including Sparkle and potentially hiding from the Dock in my todo list. Thanks!

**Comment by valeIT** [comment]
The update is up, same link as the original download.

**Comment by alxndrsbrwn** [comment]
Love the changes. Great work. Thank you. I hope you'll get the option to remove from dock in there someday. 👍🏻

**Comment by grantavery** [comment]
I would also love it if you could add a hide from Dock option!

**Comment by valeIT** [comment]
Hey, I [just released version 1.1](http://www.valentinourbano.com/Free-My-Desktop-1-1.html)!
