### ISSUE TITLE
Comments: Free My Desktop - Update 1.2.1

### ISSUE THREAD

**Issue by valeIT** [valeIT/valeIT.github.io#21]
Link: http://www.valentinourbano.com/Free-My-Desktop-1-2-1.html

**Comment by Lincoln12w** [comment]
When choose ’hide the desktop‘, all windows that not fullscreen were missing. And sometimes I could not get them back or open a new app that is not fullscreen by default, even clicked 'show the desktop' or restart the app. Finally, restart the computer solved this! My osx version is 10.14.2, is this a BUG under this version?

**Comment by valeIT** [comment]
Never seen it myself. I'm using the app at least once a week on 10.14.3 If you mean Finder.app windows that is necessary to hide the desktop unfortunately. Otherwise let me know which apps are affected so I can try to reproduce it.

Edit: Next time please use the support page to open a ticket instead of writing a comment.
