### ISSUE TITLE
Store Description

### ISSUE THREAD

**Issue by valeIT** [valeIT/valeIT.github.io#60]
#Play Store Description

## Introducing Teria

Features: 
- Streaks
- Calendar View
- Full Text Search
- RTF Support
- Works Offline
- Export Notes

Teria was born as a super minimal note application. Open the app and write. I'm a big proponent of writing your ideas down as quickly as possible so you don't forget them. 

Teria helps you accomplish that.

### Streak

Having a steak to keep you accountable. In Teria you get a steak by doing: You have to actually put in the work to get it.

Teria was born as a place to jolt down ideas, because of that the default word count for a streak is set at 250 words per day. That doesn't mean that you can't go over! You can also edit the number of words from Settings.

The streak is there to hold you accountable to yourself. It is also off by default since I don't want to pass the idea that you can use Teria only if you want to keep a streak. Use it as you wish. Keeping a streak helps me writing more, but it might not be the right fit for everyone.

### Calendar

You can choose to see your notes as a chronological list or inside a calendar. The calendar lets you see on which day you've written anything and the days you did not. The list provides a more classic look and feel.

### Other (Full Text Search + Rich Text)

Both lists include full text search across every single note. You can use it to filter across the tile and the full plain text version of the note.

Teria also supports rich text out of the box. From bold to ordered lists to quotes.

-----

# PH Description

- Write as soon as you open the app
- Search through your notes using full text search
- Track your writing through the weeks and months using the calendar view
- Get motivated to write by keeping a streak
- Export notes
- Rich text support

Comment:

Teria is a minimal note taking app that opens directly into the editor ready to type in. I use it to jolt down ideas all the time. On top of that it offers a calendar with streaks to see how much you’ve written each day.

Write Instantly

Most note apps force you to go through multiple screens to be able to write. With Teria you just need to open the app and it automatically starts a new note with the cursor blinking, waiting for your input. When you come back to out again you will find your note waiting.

[Customizable from Settings]
Steak

You can pick a word Target for you to reach each day and the app will always show you how far away are you from reaching it and how many days in a row you’ve reached it

[Customizable from Settings]
Calendar View

Easily see how much and what you’ve written each day through the calendar view.

More Info: http://www.valentinourbano.com/Introducing-Teria
More Screens: https://imgur.com/a/D5NV7GE

**Comment by valeIT** [comment]
Some more ideas:

Teria is a focused note taking app. You can use Teria to write notes, messages, memos, and e-mails, but also shopping lists to-do lists thanks to its rich text offering. 

Teria opens ready to write, reducing the friction to get the words down.

Your in-progress note is always backed up so even if you forget to save your note will be there the next time you come back.

Share your notes with any third party app including Google Keep, Notes, Wordpress, GMail, Whatsapp, Outlook and more.

Teria is available on both smartphones(iPhone) and tablets(iPad).

You can search through your notes with full text search allowing you to find what you're looking for with ease.

[Android]
Permissions Notice
- Storage Permission
Required to save notes to file.

--

Some Inspiration from other major note taking apps.

Android:
https://play.google.com/store/apps/details?id=com.google.android.keep
https://play.google.com/store/apps/details?id=com.microsoft.office.onenote
https://play.google.com/store/apps/details?id=com.samsung.android.app.notes
https://play.google.com/store/apps/details?id=com.evernote

iOS:
https://apps.apple.com/us/app/byword/id482063361
https://apps.apple.com/us/app/ia-writer/id775737172
https://apps.apple.com/us/app/ulysses/id1225571038
https://apps.apple.com/us/app/bear/id1016366447

**Comment by MsSlacker** [comment]
You lack a "." in the "share" line.
